import React, { useEffect, useState } from "react";
import {
  ArrowDown,
  ArrowRight,
  Blocks,
  Bot,
  Box,
  Check,
  ChevronRight,
  ClipboardCheck,
  Cog,
  Cpu,
  Factory,
  Gauge,
  Mail,
  Menu,
  Network,
  PenTool,
  Settings2,
  ShieldCheck,
  X,
} from "lucide-react";

const serviceIcons = [PenTool, Bot, Cog, Box, Blocks, ClipboardCheck];
const industryIcons = [Factory, Settings2, Cog, Bot, Gauge, Cpu];
const languageOptions = [
  ["en", "English"],
  ["fr", "Français"],
  ["it", "Italiano"],
];

const translations = {
  en: {
    language: "Language",
    nav: [["Services", "services"], ["Process", "process"], ["Industries", "industries"], ["About", "about"], ["Contact", "contact"]],
    discuss: "Discuss a Project",
    menu: "Toggle navigation",
    hero: {
      eyebrow: "End-to-end technical solutions",
      line1: "Industrial Engineering.",
      line2: "Automation.",
      line3: "Prototyping. Integration.",
      copy: "We help companies transform technical challenges and product ideas into complete engineered solutions, from diagnosis and concept design to prototype, automation, assembly, and delivery.",
      services: "Our Services",
      strengths: [["01", "Engineering-led"], ["02", "Supplier-independent"], ["03", "Delivery-focused"]],
    },
    services: {
      eyebrow: "Capabilities",
      title: "Engineering support across the full project lifecycle.",
      copy: "From an unresolved production issue to a commissioned machine, we bring the technical disciplines and delivery structure needed to move forward.",
      note: "One accountable engineering partner. The right specialists assembled around each challenge.",
      cards: [
        ["Engineering Consulting", "Technical diagnosis, feasibility studies, concept development, and expert guidance for complex industrial challenges."],
        ["Automation & Robotics", "Automation cells, robotic applications, controls, and process improvements built around your production reality."],
        ["Special Machine Development", "Purpose-built machines and fixtures engineered for unique products, processes, and performance requirements."],
        ["Prototype Development", "Functional prototypes that validate mechanics, electronics, software, manufacturability, and commercial potential."],
        ["Assembly & Integration", "Hands-on assembly, supplier coordination, system integration, commissioning, and production support."],
        ["Technical Project Management", "Clear technical leadership across scope, suppliers, schedules, risks, documentation, testing, and delivery."],
      ],
    },
    process: {
      eyebrow: "How we work",
      title: "A direct path from uncertainty to a working solution.",
      copy: "Every project is different. The logic is consistent: define the real problem, build the right solution, and verify that it performs.",
      steps: [
        ["01", "Diagnose", "Understand the challenge, constraints, targets, and current system."],
        ["02", "Design", "Define the concept, architecture, specifications, and delivery path."],
        ["03", "Build the Team", "Select the right technical specialists, suppliers, and production partners."],
        ["04", "Prototype / Implement", "Turn the concept into a functional prototype or integrated solution."],
        ["05", "Test & Deliver", "Validate performance, document the system, and support final deployment."],
      ],
    },
    industries: {
      eyebrow: "Industries",
      title: "Built for industrial reality.",
      copy: "We support established manufacturers and ambitious product teams where mechanical, electrical, software, and operational requirements meet.",
      link: "Tell us about your application",
      items: ["Manufacturing", "Industrial Equipment", "Special Machines", "Robotics", "Pumps & Fluid Systems", "Hardware Startups"],
    },
    about: {
      label1: "One partner.",
      label2: "Multidisciplinary execution.",
      eyebrow: "About Synertia",
      title: "Your flexible engineering department.",
      p1: "Synertia Solutions brings together multidisciplinary expertise in mechatronics, electronics, automation, software, mechanical design, logistics, and supplier coordination.",
      p2: "We act as a flexible engineering partner for companies that need complete technical solutions without building a full internal engineering department.",
      points: ["Independent technical advice", "Scalable specialist teams", "Single point of coordination", "Practical delivery ownership"],
    },
    contact: {
      eyebrow: "Start a conversation",
      title: "Have an industrial challenge or product idea?",
      copy: "Let's discuss how to turn it into a working solution.",
      scopeTitle: "Cross-disciplinary scope",
      scopeCopy: "Mechanical, electrical, controls, software, and delivery.",
      privacyTitle: "Confidential by default",
      privacyCopy: "Your technical brief is handled with professional discretion.",
      successTitle: "Project brief noted.",
      successCopy: "This demonstration form is static. Connect it to your preferred form service before launch.",
      again: "Send another message",
      name: "Name",
